# Generated by Django 5.2.14 on 2026-05-24 13:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0005_webhooksubscription_webhookdelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverProfileRefreshProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('proposed_changes', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField(blank=True)),
                ('evidence_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_payload', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_profile_refresh_proposals', to='comms.organization')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_refresh_proposals', to='comms.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_profile_refresh_proposals', to='comms.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
