# Generated by Django 5.2.14 on 2026-06-03 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0006_receiverprofilerefreshproposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_context', models.JSONField(blank=True, default=dict)),
                ('current_priorities', models.JSONField(blank=True, default=list)),
                ('communication_patterns', models.JSONField(blank=True, default=list)),
                ('customer_segments', models.JSONField(blank=True, default=list)),
                ('known_constraints', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='comms.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('meeting_type', models.CharField(blank=True, max_length=80)),
                ('cadence', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('recurring', 'Recurring'), ('recent', 'Recent'), ('paused', 'Paused')], default='recurring', max_length=30)),
                ('participants', models.JSONField(blank=True, default=list)),
                ('related_projects', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('decisions', models.JSONField(blank=True, default=list)),
                ('open_questions', models.JSONField(blank=True, default=list)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_contexts', to='comms.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_meetings', to='comms.employee')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_contexts', to='comms.team')),
            ],
            options={
                'ordering': ['organization__name', 'title'],
                'unique_together': {('organization', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ProjectContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('blocked', 'Blocked'), ('paused', 'Paused'), ('done', 'Done')], default='active', max_length=30)),
                ('priority', models.CharField(blank=True, max_length=40)),
                ('quarter', models.CharField(blank=True, max_length=40)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('stakeholders', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='comms.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to='comms.employee')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='comms.team')),
            ],
            options={
                'ordering': ['organization__name', 'status', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
